app:
  #AIzaSyDlgLWaQC32mSix98xD39r2eVb_bWkGu_Y
  name: "dost"
  version: "1.0.0"
  port: 8080
  debug: false
logger:
  level: "info"
  format: "json"

ORCHESTRATOR:
  API_KEY: "AIzaSyD0Ax4SJ9cOHRWpacw7mo-jIf5LXbxp1R8"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"

CODER:
  API_KEY: "AIzaSyD0Ax4SJ9cOHRWpacw7mo-jIf5LXbxp1R8"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"

CRITIC:
  API_KEY: "AIzaSyBXLOLaUQ2f1RLlCJtdnoWaX4eov3boj5k"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"

EXECUTOR:
  API_KEY: "AIzaSyBXLOLaUQ2f1RLlCJtdnoWaX4eov3boj5k"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"

PLANNER:
  API_KEY: "AIzaSyBXLOLaUQ2f1RLlCJtdnoWaX4eov3boj5k"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"

ANALYSIS:
  API_KEY: "AIzaSyD0Ax4SJ9cOHRWpacw7mo-jIf5LXbxp1R8"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"

#Add The model informations here
# orchestrator
ai:
  API_KEY: "AIzaSyBXLOLaUQ2f1RLlCJtdnoWaX4eov3boj5k"
  ORGANIZATION: "google"
  MODEL: "gemini-2.0-flash"
ROOT:
  API_KEY: "AIzaSyBXLOLaUQ2f1RLlCJtdnoWaX4eov3boj5k"
  ORGANIZATION: "google"
  MODEL: "gemini-2.5-flash"

assistant:
  API_KEY: "sk-a6a5839bfdb44f6d9b5191892a267d48"
  ORGANIZATION: "deepseek"
  MODEL: "deepseek-chat"
